### ISSUE TITLE
Any value can be passed to `clientIdFromToken`

### ISSUE THREAD

**Issue by cainthebest** [ghostdevv/jellycommands#167]
### Describe the bug

Its possible to pass anything to token at runtime
https://github.com/ghostdevv/jellycommands/blob/6cd717cde9ac359b5dbb52514bbe485a8a3ff615/packages/jellycommands/src/utils/token.ts#L7

This will run on any value that is passed to token
```ts
Buffer.from(token.split('.')[0], 'base64').toString();
```

### Reproduction

```ts
    const notString = clientIdFromToken(1234567890);

    assert.strictEqual(notString, null);
```

### System Info

```bash
N/A
```

**Comment by ghostdevv** [comment]
Since this function is internal, we probably don't need any checking of the value given - however it still may be possible to get a value to that function that isn't a string if we aren't checking types in other places

would be worth looking into that

**Comment by cainthebest** [comment]
After looking into it more this seems to be the case where it is relying on another function to catch a value that is not a string. Token is caught by `cleanToken` here
https://github.com/ghostdevv/jellycommands/blob/6cd717cde9ac359b5dbb52514bbe485a8a3ff615/packages/jellycommands/src/JellyCommands.ts#L48


`cleanToken` ref:
https://github.com/ghostdevv/jellycommands/blob/6cd717cde9ac359b5dbb52514bbe485a8a3ff615/packages/jellycommands/src/utils/token.ts#L3

**Comment by ghostdevv** [comment]
Ok awesome! It's definitely a bit fragile but I am happy with that for the time beind
