### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by ghostdevv** [ghostdevv/jellycommands#183]
Now we are expanding beyond just commands/events to include buttons (#171) and soon things like modals (#182) it may make sense to not require a new directory per item.

Instead of
```
commands/
buttons/
modals/
...
```

```
features/
```

> Name "features" is a work in progress, but seen it in other frameworks

Pros:
- One place for all items
- Less documentation needed

Cons:
-

Let me know any feedback/ideas

**Comment by cainthebest** [comment]
Possible suggestion for name: components

**Comment by ghostdevv** [comment]
Suggestion: `app`

**Comment by ghostdevv** [comment]
Revisiting this, I think the requirements are:

- [ ] Single directory in options (show in migration guide how to re-create old behaviour)
- [ ] All exports are checked rather than requiring the default
- [ ] Single "feature" (or w/e name is) class that items derive from, using a symbol to avoid instanceof. I think gives room for a potential plugins system in the future.

Name is still TBD

**Comment by ghostdevv** [comment]
After spending a lot of time writing the pr and calling it `features` I am used to it, but still doesn't feel right.

More ideas:
- bits
- pieces ([sapphire uses this kinda](https://www.sapphirejs.dev/docs/Documentation/api-pieces/))

I'm not sure what out of all the ideas in this thread I'm leaning to atm, so please share more ideas if anyone has any

**Comment by ghostdevv** [comment]
Decided to name it `components`, thanks for the suggestion cain!

**Comment by ghostdevv** [comment]
Added in #206, released in v`1.0.0-next.44`, [migration guide here](https://jellycommands.dev/guide/migrate/components)
