### ISSUE TITLE
JellyOptions type errors

### ISSUE THREAD

**Issue by cainthebest** [ghostdevv/jellycommands#184]
### Describe the bug

When passing events, commands or buttons to jelly client directly you need to convert the type

For example to currently workaround
```ts
// ./events/ready.ts
import { event, type Event } from 'jellycommands';

export default event({
  name: 'ready',
  run: (_, client) => {
    console.log(client.user?.tag + ' is online.');
  },
}) as Event;
```
```ts
// ./index.ts
import { JellyCommands } from 'jellycommands';
import { IntentsBitField } from 'discord.js';

import ready from './events/ready';

const client = new JellyCommands({
  // commands,
  // buttons,
  events: [ready],
});
```
This is the same for commands and buttons

### Reproduction

Import a command, button or event and pass it to jellycommands and you will be greeted with a type error.

### System Info

```bash
n/a
```

**Comment by ghostdevv** [comment]
Only seems to happen for commands and events, for different reasons both down to their generics

**Comment by cainthebest** [comment]
my mistake ide was out of sync with errors, but possible fix could be to change option types to
```ts
    // all command variations extend base command
    commands?: string | Array<string | Command | MessageCommand | UserCommand>;
    events?: string | Array<string | Event<any>>;
 ```

**Comment by ghostdevv** [comment]
That would work but it isn't ideal, it should work having `BaseCommand` there as they all inherit from it - `Event<any>` shouldn't need the `any` to work, need to take a look at why it's doing that
