### ISSUE TITLE
Guards update

### ISSUE THREAD

**Issue by ghostdevv** [ghostdevv/jellycommands#9]
### Describe the feature

Update guards:

```ts
interface _ {
        mode: 'whitelist' | 'blacklist';

        users?: string[];

        roles?: string[];
}
```

### Checklist
- [x] Users
- [x] Roles

**Comment by ghostdevv** [comment]
Poll:
Should permissions just be required permissions? like for example you have:
```js
guards: {
    permissions: ['ADMINISTRATOR']
}
```
meaning you must have administrator, instead of `requiredPermissions` and `blockedPermissions`

**Comment by cainthebest** [comment]
I think the current way you have implemented it is perfectly fine for now as its customisable for many needs. 

Do they have a default?
And are they optional so if the developer wants all roles and have all permissions allowed there would be no need for this to be passed in the “command options”.

**Comment by ghostdevv** [comment]
> I think the current way you have implemented it is perfectly fine for now as its customisable for many needs.

Oki

> Do they have a default?
And are they optional so if the developer wants all roles and have all permissions allowed there would be no need for this to be passed in the “command options”/ guards.

Everything is optional, I fixed the types to show this

**Comment by ghostdevv** [comment]
Updated to reflect slash command switch
